controller_manager:
  ros__parameters:

    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    io_and_status_controller:
      type: ur_controllers/GPIOController

    speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    pan_tilt_controller:
      type: joint_trajectory_controller/JointTrajectoryController


speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0
    tf_prefix: "ur5e"

io_and_status_controller:
  ros__parameters:
    tf_prefix: "ur5e"

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: ur5etcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: ur5etool0
    topic_name: ft_data


joint_trajectory_controller:
  ros__parameters:
    joints:
      - ur5eshoulder_pan_joint
      - ur5eshoulder_lift_joint
      - ur5eelbow_joint
      - ur5ewrist_1_joint
      - ur5ewrist_2_joint
      - ur5ewrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      ur5eshoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      ur5eshoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      ur5eelbow_joint: { trajectory: 0.2, goal: 0.1 }
      ur5ewrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      ur5ewrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      ur5ewrist_3_joint: { trajectory: 0.2, goal: 0.1 }


scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - ur5eshoulder_pan_joint
      - ur5eshoulder_lift_joint
      - ur5eelbow_joint
      - ur5ewrist_1_joint
      - ur5ewrist_2_joint
      - ur5ewrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      ur5eshoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      ur5eshoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      ur5eelbow_joint: { trajectory: 0.2, goal: 0.1 }
      ur5ewrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      ur5ewrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      ur5ewrist_3_joint: { trajectory: 0.2, goal: 0.1 }
    speed_scaling_interface_name: ur5espeed_scaling/speed_scaling_factor

forward_velocity_controller:
  ros__parameters:
    joints:
      - ur5eshoulder_pan_joint
      - ur5eshoulder_lift_joint
      - ur5eelbow_joint
      - ur5ewrist_1_joint
      - ur5ewrist_2_joint
      - ur5ewrist_3_joint
    interface_name: velocity

forward_position_controller:
  ros__parameters:
    joints:
      - ur5eshoulder_pan_joint
      - ur5eshoulder_lift_joint
      - ur5eelbow_joint
      - ur5ewrist_1_joint
      - ur5ewrist_2_joint
      - ur5ewrist_3_joint
pan_tilt_controller:
  ros__parameters:
    joints:
      - pan_tilt_pan_motor_joint
      - pan_tilt_tilt_motor_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      pan_tilt_pan_motor_joint: { trajectory: 0.2, goal: 0.1 }
      pan_tilt_tilt_motor_joint: { trajectory: 0.2, goal: 0.1 }
